defaults:
 snmp_version: "v2c"
 timeout_s: 2.5
 retries: 1
 target_budget_s: 10
 oids:
   - "sysUpTime.0"
   - "sysName.0"


targets:
#Linn, Amanda
 - name: "switch-251"
   ip: "172.16.0.251"
   community: "public"
   oids:
     - "sysDescr.0"
     - "ifOperStatus.1"

#Magica
 - name: "switch-235"
   ip: "172.16.0.235"
   community: "public"
   oids:
     - "sysDescr.0"
     - "ifOperStatus.1"

#Marla
 - name: "switch-181"
   ip: "172.16.0.181"
   community: "public"
   oids:
     - "sysDescr.0"
     - "ifOperStatus.1"

#Felicia
 - name: "switch-157"
   ip: "172.16.0.157"
   community: "public"
   oids:
     - "sysDescr.0"
     - "ifOperStatus.1"
